//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArizaTakipMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gorev
    {
        public int id_Gorev { get; set; }
        public short id_GorevDurumTur { get; set; }
        public int id_Kullanici { get; set; }
        public string GorevAciklama { get; set; }
        public System.DateTime GorevBasTarihi { get; set; }
        public System.DateTime GorevBitTarihi { get; set; }
    
        public virtual tbl_GorevDurumTur tbl_GorevDurumTur { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
    }
}
